import { promises as fs } from 'fs';
import path from 'path';

export type CacheableSection =
    | 'hero'
    | 'about'
    | 'contact'
    | 'skills'
    | 'experience'
    | 'projects'
    | 'product-projects'
    | 'blog'
    | 'settings'
    | 'resume'
    | 'cover-letter';

export const CACHEABLE_SECTIONS: { value: CacheableSection; label: string }[] = [
    { value: 'hero', label: 'Hero Section' },
    { value: 'about', label: 'About' },
    { value: 'contact', label: 'Contact' },
    { value: 'skills', label: 'Skills' },
    { value: 'experience', label: 'Experience' },
    { value: 'projects', label: 'Projects' },
    { value: 'product-projects', label: 'Products' },
    { value: 'blog', label: 'Blog Posts' },
    { value: 'settings', label: 'Settings' },
    { value: 'resume', label: 'Resume' },
    { value: 'cover-letter', label: 'Cover Letter' },
];

const CACHE_DIR = path.resolve(process.cwd(), 'app/lib/cache-data');
const LEGACY_CACHE_FILE = path.resolve(process.cwd(), 'app/lib/cache-data.ts');

/**
 * Read the cache directory and return its contents.
 * Returns empty object if it doesn't exist or on error.
 */
export async function readCache(): Promise<Record<string, unknown>> {
    try {
        const cache: Record<string, unknown> = {};
        
        try {
            await fs.mkdir(CACHE_DIR, { recursive: true });
        } catch {}

        const files = await fs.readdir(CACHE_DIR);
        for (const file of files) {
            if (file.endsWith('.ts')) {
                const sectionName = file.replace('.ts', '');
                const filePath = path.join(CACHE_DIR, file);
                try {
                    const content = await fs.readFile(filePath, 'utf-8');
                    const jsonStart = content.indexOf('{');
                    const jsonEnd = content.lastIndexOf('}');
                    if (jsonStart !== -1 && jsonEnd !== -1 && jsonEnd > jsonStart) {
                        const jsonStr = content.slice(jsonStart, jsonEnd + 1);
                        cache[sectionName] = JSON.parse(jsonStr);
                    }
                } catch (err) {
                    console.error(`Failed to parse cache file for section ${sectionName}:`, err);
                }
            }
        }
        return cache;
    } catch {
        return {};
    }
}

/**
 * Write the cache file with the provided data.
 */
export async function writeCache(data: Record<string, unknown>): Promise<void> {
    await fs.mkdir(CACHE_DIR, { recursive: true });

    const currentKeys = Object.keys(data);
    for (const key of currentKeys) {
        const filePath = path.join(CACHE_DIR, `${key}.ts`);
        const tsContent = `// This file is auto-generated by the cache manager. Do not edit directly.
export const cacheData = ${JSON.stringify(data[key], null, 2)};
export default cacheData;
`;
        await fs.writeFile(filePath, tsContent, 'utf-8');
    }

    try {
        const files = await fs.readdir(CACHE_DIR);
        for (const file of files) {
            if (file.endsWith('.ts')) {
                const sectionName = file.replace('.ts', '');
                if (!currentKeys.includes(sectionName)) {
                    await fs.unlink(path.join(CACHE_DIR, file));
                }
            }
        }
    } catch {}

    try {
        const dummyContent = `// Legacy file. Do not edit directly.
export const cacheData = {};
export default cacheData;
`;
        await fs.writeFile(LEGACY_CACHE_FILE, dummyContent, 'utf-8');
    } catch {}
}

interface CacheWrapper<T> {
    data: T;
    _cachedAt: string;
    _type: 'array' | 'object';
}

/**
 * Get the cached data for a specific section.
 * Returns the actual data (unwrapped from the CacheWrapper) or null if not found.
 * Handles both the new wrapper format and legacy raw data format.
 */
export async function getCachedSection<T>(section: CacheableSection): Promise<T | null> {
    try {
        const cache = await readCache();
        const entry = cache[section];
        if (entry === null || entry === undefined) return null;

        // New wrapper format: { data, _cachedAt, _type }
        if (
            typeof entry === 'object' &&
            entry !== null &&
            'data' in (entry as object) &&
            '_cachedAt' in (entry as object)
        ) {
            return (entry as CacheWrapper<T>).data ?? null;
        }

        // Legacy fallback: return raw entry as-is
        return entry as T;
    } catch {
        return null;
    }
}

/**
 * Set cache data for a specific section.
 * Wraps the data in a CacheWrapper with metadata.
 */
export async function setCachedSection<T>(section: CacheableSection, data: T): Promise<void> {
    if (data === null || data === undefined) return;
    const cache = await readCache();
    const isArray = Array.isArray(data);
    cache[section] = {
        data,
        _cachedAt: new Date().toISOString(),
        _type: isArray ? 'array' : 'object',
    } as unknown;
    await writeCache(cache);
}

/**
 * Clear a specific section from the cache.
 */
export async function clearCacheSection(section: CacheableSection): Promise<void> {
    const cache = await readCache();
    if (section in cache) {
        delete cache[section];
        await writeCache(cache);
    }
}

/**
 * Clear all cache.
 */
export async function clearAllCache(): Promise<void> {
    await writeCache({});
}

/**
 * List all currently cached sections.
 */
export async function listCachedSections(): Promise<CacheableSection[]> {
    const cache = await readCache();
    return Object.keys(cache) as CacheableSection[];
}

