// This file is auto-generated by the cache manager. Do not edit directly.
export const cacheData = {
  "data": {
    "_id": "694aac49db3a970f9e2f004f",
    "bio": "<div style=\"text-align: center;\"><span style=\"font-family: &quot;Bricolage Grotesque&quot;, &quot;Bricolage Grotesque Fallback&quot;; font-size: 1rem;\">I’m <b>Joshua</b>, a multidisciplinary technologist passionate about transforming complexity into clarity. My journey bridges three worlds: <b>Data Analytics &amp; Science/Web</b> — uncovering insights, building predictive models, and translating raw data into actionable strategies. <b>AI/ML/DL</b> Engineering — designing intelligent systems, training deep learning architectures, and pushing the boundaries of machine learning applications. Full Stack Development — crafting scalable, user-focused applications from front-end design to back-end infrastructure. What drives me is curiosity and impact. I thrive on solving problems that matter — whether it’s optimizing workflows, automating decisions, or creating digital products that empower people. Beyond the code, I value collaboration, continuous learning, and the art of connecting ideas across disciplines. My portfolio is a reflection of that mindset: a space where data meets design, and innovation meets execution. In short: I don’t just build solutions — I engineer possibilities.</span></div>",
    "socialLinks": [
      {
        "platform": "github",
        "url": "http://github.com/Akinleyejoshua",
        "icon": "github"
      },
      {
        "platform": "turing",
        "url": "https://matching.turing.com/developer-resume-preview/94fcd098ef28063a611a36b6c211b83394302204b3221e",
        "icon": "linkedin"
      },
      {
        "platform": "Twitter",
        "url": "https://x.com/yeshuaakinleye",
        "icon": ""
      },
      {
        "platform": "Linkedin",
        "url": "https://www.linkedin.com/in/joshua-akinleye-061a013a6/",
        "icon": ""
      },
      {
        "platform": "Facebook",
        "url": "https://www.facebook.com/akinleye.joshua2",
        "icon": ""
      },
      {
        "platform": "Instagram",
        "url": "https://www.instagram.com/joshua_akinleye",
        "icon": ""
      },
      {
        "platform": "Tiktok",
        "url": "https://www.tiktok.com/@joshua_akinleye",
        "icon": ""
      },
      {
        "platform": "youtube",
        "url": "https://www.youtube.com/@akinleyejoshua1785",
        "icon": "link"
      },
      {
        "platform": "Whatsapp",
        "url": "https://wa.me/message/AMD7EGWCFIF5I1",
        "icon": "link"
      }
    ],
    "createdAt": "2025-12-23T14:50:49.111Z",
    "updatedAt": "2026-06-13T12:04:51.661Z",
    "__v": 0
  },
  "_cachedAt": "2026-06-16T23:59:45.785Z",
  "_type": "object"
};
export default cacheData;
