// This file is auto-generated by the cache manager. Do not edit directly.
export const cacheData = {
  "data": {
    "_id": "694aac49db3a970f9e2f0062",
    "email": "akinleyejoshua.career@gmail.com",
    "phone": "23408131519518",
    "createdAt": "2025-12-23T14:50:49.660Z",
    "updatedAt": "2026-06-13T18:44:08.334Z",
    "__v": 0
  },
  "_cachedAt": "2026-06-16T23:59:46.055Z",
  "_type": "object"
};
export default cacheData;
