// This file is auto-generated by the cache manager. Do not edit directly.
export const cacheData = {
  "data": [
    {
      "_id": "694aac49db3a970f9e2f0051",
      "role": "Web Developer",
      "company": "C.A.C",
      "startDate": "2020-01-01T00:00:00.000Z",
      "endDate": "2021-12-31T00:00:00.000Z",
      "isCurrent": false,
      "description": [
        "Designed and developed responsive web applications",
        "Collaborated with teams to deliver client solutions",
        "Implemented front-end interfaces using modern frameworks"
      ],
      "order": 0,
      "__v": 0,
      "createdAt": "2025-12-23T14:50:49.288Z",
      "updatedAt": "2025-12-23T14:50:49.288Z"
    },
    {
      "_id": "694aac49db3a970f9e2f0052",
      "role": "Full Stack Developer",
      "company": "Gtext",
      "startDate": "2021-01-01T00:00:00.000Z",
      "endDate": "2022-12-31T00:00:00.000Z",
      "isCurrent": false,
      "description": [
        "Developed end-to-end web applications",
        "Built RESTful APIs and managed databases",
        "Deployed production-ready applications"
      ],
      "order": 1,
      "__v": 0,
      "createdAt": "2025-12-23T14:50:49.289Z",
      "updatedAt": "2025-12-23T14:50:49.289Z"
    },
    {
      "_id": "694aac49db3a970f9e2f0053",
      "role": "Conversational A.I Scientist (Data Science)",
      "company": "Smartecniqs",
      "startDate": "2022-01-01T00:00:00.000Z",
      "endDate": "2023-12-31T00:00:00.000Z",
      "isCurrent": false,
      "description": [
        "Developed conversational AI systems",
        "Built and trained machine learning models",
        "Implemented NLP solutions for business applications"
      ],
      "order": 2,
      "__v": 0,
      "createdAt": "2025-12-23T14:50:49.289Z",
      "updatedAt": "2025-12-23T14:50:49.289Z"
    },
    {
      "_id": "694aac49db3a970f9e2f0054",
      "role": "Backend Developer",
      "company": "BLNR (Open Source)",
      "startDate": "2024-01-01T00:00:00.000Z",
      "endDate": "2025-12-24T00:00:00.000Z",
      "isCurrent": false,
      "description": [
        "Leading backend architecture and development",
        "Contributing to open source projects",
        "Designing scalable server-side solutions",
        "Collaborating with IT teams to meet client expectations"
      ],
      "order": 3,
      "__v": 0,
      "createdAt": "2025-12-23T14:50:49.289Z",
      "updatedAt": "2026-01-06T19:12:18.813Z"
    },
    {
      "_id": "695e7edd926ccba002516aac",
      "role": "Full Stack Developer",
      "company": "Corvendra",
      "startDate": "2026-01-07T00:00:00.000Z",
      "endDate": null,
      "isCurrent": true,
      "description": [
        "i) Software Design & Development",
        "ii) Front-End Engineering",
        "iii) Back-End Development",
        "iv) Integration, Deployment & Maintenance",
        "v) Collaboration & Cross-Functional Support",
        "vi) Security & Compliance"
      ],
      "order": 4,
      "createdAt": "2026-01-07T15:42:21.073Z",
      "updatedAt": "2026-04-24T17:56:41.473Z",
      "__v": 0
    }
  ],
  "_cachedAt": "2026-06-16T23:59:46.512Z",
  "_type": "array"
};
export default cacheData;
