// This file is auto-generated by the cache manager. Do not edit directly.
export const cacheData = {
  "data": {
    "_id": "694aac48db3a970f9e2f004d",
    "headline": "Turning data into decisions & scalable solutions.  ",
    "subtext": "I’m Joshua — a Data Analytics Scientist, AI/ML/DL Engineer, and Full Stack Developer. My craft lies at the intersection of intelligence and innovation: building predictive models that learn, designing systems that scale, and developing applications that empower.",
    "primaryCtaText": "View Projects",
    "primaryCtaLink": "#projects",
    "secondaryCtaText": "Get In Touch",
    "secondaryCtaLink": "#contact",
    "heroImage": "https://ultraspacetech.vercel.app/team-ceo.jpg",
    "createdAt": "2025-12-23T14:50:48.906Z",
    "updatedAt": "2026-06-17T00:20:54.756Z",
    "__v": 0
  },
  "_cachedAt": "2026-06-17T00:21:23.173Z",
  "_type": "object"
};
export default cacheData;
