// This file is auto-generated by the cache manager. Do not edit directly.
export const cacheData = {
  "data": {
    "_id": "694aac48db3a970f9e2f004d",
    "headline": "Turning data into decisions & scalable solutions.  ",
    "subtext": "I’m Joshua — a Data Analytics Scientist, AI/ML/DL Engineer, and Full Stack Developer. My craft lies at the intersection of intelligence and innovation: building predictive models that learn, designing systems that scale, and developing applications that empower.",
    "primaryCtaText": "View Projects",
    "primaryCtaLink": "#projects",
    "secondaryCtaText": "Get In Touch",
    "secondaryCtaLink": "#contact",
    "heroImage": "https://media-gallery.free.nf/uploads/1781901041-9033b36da11f64c5e4e3f85ab2709c1d.jpeg",
    "createdAt": "2025-12-23T14:50:48.906Z",
    "updatedAt": "2026-06-19T20:30:53.753Z",
    "__v": 0
  },
  "_cachedAt": "2026-06-19T20:30:53.973Z",
  "_type": "object"
};
export default cacheData;
