// This file is auto-generated by the cache manager. Do not edit directly.
export const cacheData = {
  "data": {
    "_id": "6a0812ef6488621b1232427a",
    "fontFamily": "Bricolage Grotesque",
    "fontSize": 14,
    "fontWeight": 400,
    "accentColor": "#f97316",
    "createdAt": "2026-05-16T06:47:11.981Z",
    "updatedAt": "2026-06-16T22:43:01.279Z",
    "__v": 0,
    "projectsLimit": 4,
    "enableCache": true
  },
  "_cachedAt": "2026-06-17T00:00:16.512Z",
  "_type": "object"
};
export default cacheData;
