export { Header } from './header';
export { Hero } from './hero';
export { About } from './about';
export { Experience } from './experience';
export { CategoryTabs } from './category-tabs';
export { Carousel } from './carousel';
export { Projects } from './projects';
export { Contact } from './contact';
export { Footer } from './footer';
